#include "cardsetting.h"

Cardsetting::Cardsetting(int x)
{
    ID = x;

    switch(ID){
        case 0: //for cancel picked
            ori_hp = 0;
            cur_hp = 0;
            shell = 0;
            attack = 0;
            torpedo = 0;
            air_atk = 0;
            sub_atk = 0;
            double_atk = 0;
            air_strike = false;
            sub_strike = false;
            tor_strike = false;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/cancelselection.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            break;
        case 1: //nagato
            ori_hp = 91;
            cur_hp = ori_hp;
            shell = 110;
            attack = 118;
            torpedo = 0;
            air_atk = 0;
            sub_atk = 0;
            double_atk = 50;
            air_strike = false;
            sub_strike = false;
            tor_strike = false;
            double_strike = true;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/nagato_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/nagato_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/nagato_battle.png"));
            break;
        case 2: //akagi
            ori_hp = 77;
            cur_hp = ori_hp;
            shell = 79;
            attack = 54;
            torpedo = 0;
            air_atk = 80;
            sub_atk = 0;
            double_atk = 0;
            air_strike = true;
            sub_strike = false;
            tor_strike = false;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/akagi_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/akagi_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/akagi_battle.png"));
            break;
        case 3: //hiyru
            ori_hp = 67;
            cur_hp = ori_hp;
            shell = 76;
            attack = 80;
            torpedo = 0;
            air_atk = 50;
            sub_atk = 0;
            double_atk = 0;
            air_strike = true;
            sub_strike = false;
            tor_strike = false;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/hiryu_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/hiryu_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/hiryu_battle.png"));
            break;
        case 4: //kitakami
            ori_hp = 43;
            cur_hp = ori_hp;
            shell = 63;
            attack = 30;
            torpedo = 150;
            air_atk = 0;
            sub_atk = 30;
            double_atk = 0;
            air_strike = false;
            sub_strike = true;
            tor_strike = true;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/kitakami_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/kitakami_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/kitakami_battle.png"));
            break;
        case 5: //kongo desu
            ori_hp = 82;
            cur_hp = ori_hp;
            shell = 90;
            attack = 90;
            torpedo = 0;
            air_atk = 0;
            sub_atk = 0;
            double_atk = 20;
            air_strike = false;
            sub_strike = false;
            tor_strike = false;
            double_strike = true;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/kongo_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/kongo_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/kongo_battle.png"));
            break;
        case 6: //ryujo
            ori_hp = 50;
            cur_hp = ori_hp;
            shell = 62;
            attack = 40;
            torpedo = 0;
            air_atk = 40;
            sub_atk = 30;
            double_atk = 0;
            air_strike = true;
            sub_strike = true;
            tor_strike = false;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/ryujo_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/ryujo_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/ryujo_battle.png"));
            break;
        case 7: //fuso
            ori_hp = 77;
            cur_hp = ori_hp;
            shell = 90;
            attack = 99;
            torpedo = 0;
            air_atk = 20;
            sub_atk = 20;
            double_atk = 10;
            air_strike = true;
            sub_strike = true;
            tor_strike = false;
            double_strike = true;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/fuso_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/fuso_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/fuso_battle.png"));
            break;
        case 8: //jintsu
            ori_hp = 40;
            cur_hp = ori_hp;
            shell = 50;
            attack = 75;
            torpedo = 98;
            air_atk = 0;
            sub_atk = 35;
            double_atk = 0;
            air_strike = false;
            sub_strike = true;
            tor_strike = true;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/jintsu_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/jintsu_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/jintsu_battle.png"));
            break;
        case 9: //abukuma <3<3<3
            ori_hp = 45;
            cur_hp = ori_hp;
            shell = 68;
            attack = 60;
            torpedo = 100;
            air_atk = 0;
            sub_atk = 30;
            double_atk = 0;
            air_strike = false;
            sub_strike = true;
            tor_strike = true;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/abukuma_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/abukuma_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/abukuma_battle.png"));
            break;
        case 10:    //kuma!
            ori_hp = 42;
            cur_hp = ori_hp;
            shell = 69;
            attack = 69;
            torpedo = 89;
            air_atk = 0;
            sub_atk = 35;
            double_atk = 0;
            air_strike = false;
            sub_strike = true;
            tor_strike = true;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/kuma_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/kuma_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/kuma_battle.png"));
            break;
        case 11:    //poi!
            ori_hp = 28;
            cur_hp = ori_hp;
            shell = 52;
            attack = 73;
            torpedo = 93;
            air_atk = 0;
            sub_atk = 45;
            double_atk = 0;
            air_strike = false;
            sub_strike = true;
            tor_strike = true;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/yudachi_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/yudachi_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/yudachi_battle.png"));
            break;
        case 12:    //akatsuki LADY
            ori_hp = 33;
            cur_hp = ori_hp;
            shell = 50;
            attack = 62;
            torpedo = 90;
            air_atk = 0;
            sub_atk = 40;
            double_atk = 0;
            air_strike = false;
            sub_strike = true;
            tor_strike = true;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/akatsuki_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/akatsuki_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/akatsuki_battle.png"));
            break;
        case 13:    //asashio prprpr
            ori_hp = 40;
            cur_hp = ori_hp;
            shell = 57;
            attack = 50;
            torpedo = 80;
            air_atk = 0;
            sub_atk = 90;
            double_atk = 0;
            air_strike = false;
            sub_strike = true;
            tor_strike = true;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/asashio_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/asashio_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/asashio_battle.png"));
            break;
        case 14:    //yubari melon
            ori_hp = 36;
            cur_hp = ori_hp;
            shell = 49;
            attack = 65;
            torpedo = 79;
            air_atk = 0;
            sub_atk = 35;
            double_atk = 35;
            air_strike = false;
            sub_strike = true;
            tor_strike = true;
            double_strike = true;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/yubari_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/yubari_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/yubari_battle.png"));
            break;
        case 15:    //suzuya
            ori_hp = 61;
            cur_hp = ori_hp;
            shell = 74;
            attack = 76;
            torpedo = 88;
            air_atk = 15;
            sub_atk = 15;
            double_atk = 0;
            air_strike = true;
            sub_strike = true;
            tor_strike = true;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/suzuya_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/suzuya_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/suzuya_battle.png"));
            break;
        case 16:    //taiho
            ori_hp = 70;
            cur_hp = ori_hp;
            shell = 84;
            attack = 59;
            torpedo = 0;
            air_atk = 70;
            sub_atk = 0;
            double_atk = 0;
            air_strike = true;
            sub_strike = false;
            tor_strike = false;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/taiho_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/taiho_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/taiho_battle.png"));
            break;
        case 17:    //isuzu
            ori_hp = 44;
            cur_hp = ori_hp;
            shell = 69;
            attack = 50;
            torpedo = 79;
            air_atk = 0;
            sub_atk = 100;
            double_atk = 0;
            air_strike = false;
            sub_strike = true;
            tor_strike = true;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/isuzu_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/isuzu_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/isuzu_battle.png"));
            break;
        case 18:    //bismarck <3<3<3<3<3
            ori_hp = 99;
            cur_hp = ori_hp;
            shell = 95;
            attack = 99;
            torpedo = 40;
            air_atk = 0;
            sub_atk = 0;
            double_atk = 50;
            air_strike = false;
            sub_strike = false;
            tor_strike = true;
            double_strike = true;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/bismarck_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/bismarck_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/bismarck_battle.png"));
            break;
        case 19:    //ro500
            ori_hp = 13;
            cur_hp = ori_hp;
            shell = 21;
            attack = 0;
            torpedo = 100;
            air_atk = 0;
            sub_atk = 0;
            double_atk = 0;
            air_strike = false;
            sub_strike = false;
            tor_strike = true;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/ro500_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/ro500_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/ro500_battle.png"));
            break;
        case 20:    //i14
            ori_hp = 22;
            cur_hp = ori_hp;
            shell = 23;
            attack = 0;
            torpedo = 120;
            air_atk = 30;
            sub_atk = 0;
            double_atk = 0;
            air_strike = true;
            sub_strike = false;
            tor_strike = true;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/i14_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/i14_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/i14_battle.png"));
            break;
        case 21:    //furutaka
            ori_hp = 60;
            cur_hp = ori_hp;
            shell = 72;
            attack = 85;
            torpedo = 75;
            air_atk = 0;
            sub_atk = 0;
            double_atk = 30;
            air_strike = false;
            sub_strike = false;
            tor_strike = true;
            double_strike = true;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/furutaka_pre.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::PointingHandCursor);
            grouppic = new QGraphicsPixmapItem(QPixmap("../project3/images/furutaka_group.png"));
            grouppic->setCursor(Qt::PointingHandCursor);
            battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/furutaka_battle.png"));
            break;
        case 22:   //locked
            ori_hp = 0;
            cur_hp = 0;
            shell = 0;
            attack = 0;
            torpedo = 0;
            air_atk = 0;
            sub_atk = 0;
            double_atk = 0;
            air_strike = false;
            sub_strike = false;
            tor_strike = false;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/locked.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::ForbiddenCursor);
            break;
        case 23:    //picked
            ori_hp = 0;
            cur_hp = 0;
            shell = 0;
            attack = 0;
            torpedo = 0;
            air_atk = 0;
            sub_atk = 0;
            double_atk = 0;
            air_strike = false;
            sub_strike = false;
            tor_strike = false;
            double_strike = false;
            previewpic = new QGraphicsPixmapItem(QPixmap("../project3/images/picked.png"));
            previewpic->setPos(200,0);
            previewpic->setCursor(Qt::ForbiddenCursor);
            break;
    case 24:    //boss
        ori_hp = 400;
        cur_hp = ori_hp;
        shell = 185;
        attack = 180;
        torpedo = 0;
        air_atk = 0;
        sub_atk = 0;
        double_atk = 50;
        air_strike = false;
        sub_strike = false;
        tor_strike = false;
        double_strike = true;
        battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/BOSS.png"));
        break;
    case 25:    //BB
        ori_hp = 90;
        cur_hp = ori_hp;
        shell = 96;
        attack = 125;
        torpedo = 0;
        air_atk = 0;
        sub_atk = 0;
        double_atk = 30;
        air_strike = false;
        sub_strike = false;
        tor_strike = false;
        double_strike = true;
        battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/BB.png"));
        break;
    case 26:    //BB
        ori_hp = 90;
        cur_hp = ori_hp;
        shell = 96;
        attack = 125;
        torpedo = 0;
        air_atk = 0;
        sub_atk = 0;
        double_atk = 30;
        air_strike = false;
        sub_strike = false;
        tor_strike = false;
        double_strike = true;
        battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/BB.png"));
        break;
    case 27:    //DD
        ori_hp = 30;
        cur_hp = ori_hp;
        shell = 30;
        attack = 15;
        torpedo = 60;
        air_atk = 0;
        sub_atk = 10;
        double_atk = 0;
        air_strike = false;
        sub_strike = true;
        tor_strike = true;
        double_strike = false;
        battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/DD.png"));
        break;
    case 28:    //DD
        ori_hp = 30;
        cur_hp = ori_hp;
        shell = 30;
        attack = 15;
        torpedo = 60;
        air_atk = 0;
        sub_atk = 10;
        double_atk = 0;
        air_strike = false;
        sub_strike = true;
        tor_strike = true;
        double_strike = false;
        battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/DD.png"));
        break;
    case 29:    //SS
        ori_hp = 40;
        cur_hp = ori_hp;
        shell = 30;
        attack = 0;
        torpedo = 70;
        air_atk = 0;
        sub_atk = 0;
        double_atk = 0;
        air_strike = false;
        sub_strike = false;
        tor_strike = true;
        double_strike = false;
        battlepic = new QGraphicsPixmapItem(QPixmap("../project3/images/SS.png"));
        break;
    }
}
